import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { afterAll, beforeAll, expect, it, vi } from "vitest";
import { defaultCourseCatalogueSection, emptyCourse } from "@/lib/course-catalogue";
let database: ReturnType<typeof drizzle>;
const actor = `catalogue-fixture-${randomUUID()}`;
vi.mock("@/server/db", () => ({ getDb: () => database }));
vi.mock("@/server/course-mail", () => ({ sendCourseMail: vi.fn(async () => ({ delivered: true })) }));
vi.mock("@/server/site-mail", () => ({ sendPrimaryInboxMail: vi.fn(async () => ({ delivered: true })) }));
vi.mock("@/server/admin-auth", async (original) => {
  const authModule = await original<typeof import("@/server/admin-auth")>();
  return { ...authModule, requireClientAdmin: async (request: Request) => {
    if (request.headers.get("x-fixture-admin") !== "yes") throw new authModule.AdminAuthError(403, "Administrator required.");
    return { session: { user: { id: actor } } };
  } };
});
import { GET, POST } from "@/app/api/admin/course-catalogue/route";
import { GET as published } from "@/app/api/course-catalogue/route";
import { GET as openOfferings, POST as register } from "@/app/api/courses/route";
import { GET as participants } from "@/app/api/admin/courses/route";
const enabled = process.env.BOOKING_DB_TESTS === "1";
let pool: Pool;
const ids: string[] = []; const categoryIds: string[] = []; const instructorId = randomUUID();
let previousSection: { document_type: string; data: Record<string, unknown>; updated_by_auth_user_id: string | null; created_at: Date; updated_at: Date } | undefined;
const input = { ...emptyCourse, title: "Catalogue fixture", slug: `catalogue-${randomUUID()}`, summary: "Practical course catalogue verification.", description: "A local verification course, not a real advertised event." };
const request = (body?: object, origin = "http://localhost:3001") => new Request("http://localhost:3001/api/admin/course-catalogue", { method: body ? "POST" : "GET", headers: { origin, "x-fixture-admin": "yes" }, ...(body ? { body: JSON.stringify(body) } : {}) });
beforeAll(async () => {
  if (!enabled) return;
  process.loadEnvFile(".env.local");
  const url = new URL(process.env.DATABASE_URL!);
  if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.port !== "55434" || url.pathname !== "/premium_web") throw new Error("Local fixture database required.");
  pool = new Pool({ connectionString: process.env.DATABASE_URL }); database = drizzle(pool);
  previousSection = (await pool.query("select * from cms_documents where key='course_catalogue_section'")).rows[0];
  await pool.query("insert into profiles(id,auth_user_id,display_name,role) values($1,$2,'Catalogue Fixture Instructor','staff')", [instructorId, actor]);
});
afterAll(async () => {
  if (!pool) return;
  await pool.query("delete from audit_logs where action='course.registration_submitted' and entity_id in (select r.id::text from course_registrations r join course_offerings o on o.id=r.offering_id where o.course_id=any($1::uuid[]))", [ids]);
  await pool.query("delete from course_offerings where course_id=any($1::uuid[])", [ids]);
  await pool.query("delete from courses where id=any($1::uuid[])", [ids]);
  await pool.query("delete from course_categories where id=any($1::uuid[])", [categoryIds]);
  await pool.query("delete from profiles where id=$1 and auth_user_id=$2", [instructorId, actor]);
  await pool.query("delete from audit_logs where actor_auth_user_id=$1", [actor]);
  if (previousSection) await pool.query("insert into cms_documents(key,document_type,data,updated_by_auth_user_id,created_at,updated_at) values('course_catalogue_section',$1,$2,$3,$4,$5) on conflict(key) do update set document_type=excluded.document_type,data=excluded.data,updated_by_auth_user_id=excluded.updated_by_auth_user_id,created_at=excluded.created_at,updated_at=excluded.updated_at", [previousSection.document_type, previousSection.data, previousSection.updated_by_auth_user_id, previousSection.created_at, previousSection.updated_at]);
  else await pool.query("delete from cms_documents where key='course_catalogue_section'");
  await pool.end();
});

it.skipIf(!enabled)("publishes the catalogue section on a selected page with a safe color or image background", async () => {
  const initial = (await (await GET(request())).json()).section;
  expect(initial).toMatchObject(defaultCourseCatalogueSection);
  expect((await POST(request({ action: "section", updatedAt: initial.updatedAt, data: { ...defaultCourseCatalogueSection, pageSlug: "home" } }, "https://untrusted.example"))).status).toBe(403);
  expect((await POST(request({ action: "section", updatedAt: initial.updatedAt, data: { ...defaultCourseCatalogueSection, pageSlug: "home", backgroundType: "image", backgroundImageUrl: "javascript:alert(1)" } }))).status).toBe(422);
  const data = { ...defaultCourseCatalogueSection, isPublished: true, pageSlug: "home" as const, backgroundType: "image" as const, backgroundImageUrl: "/images/home-hero-background-4.png", backgroundColor: "#004945" };
  const savedResponse = await POST(request({ action: "section", updatedAt: initial.updatedAt, data }));
  expect(savedResponse.status).toBe(200);
  const saved = (await savedResponse.json()).data;
  expect(saved).toMatchObject(data);
  expect((await (await published()).json()).section).toMatchObject(data);
  expect((await POST(request({ action: "section", updatedAt: initial.updatedAt, data: { ...data, isPublished: false } }))).status).toBe(409);
  const hiddenResponse = await POST(request({ action: "section", updatedAt: saved.updatedAt, data: { ...data, isPublished: false } }));
  expect(hiddenResponse.status).toBe(200);
  expect((await (await published()).json()).section.isPublished).toBe(false);
});
it.skipIf(!enabled)("persists catalogue cards, metadata, publication, duplication and safe deletion", async () => {
  expect((await GET(new Request("http://localhost:3001/api/admin/course-catalogue"))).status).toBe(403);
  expect((await POST(request({ action: "create", data: input }, "https://untrusted.example"))).status).toBe(403);
  const response = await POST(request({ action: "create", data: input })); expect(response.status).toBe(201);
  const draft = (await response.json()).data; ids.push(draft.id);
  expect((await (await published()).json()).data.some((course: { id: string }) => course.id === draft.id)).toBe(false);
  const categoryResponse = await POST(request({ action: "category", name: actor })); expect(categoryResponse.status).toBe(201);
  const category = (await categoryResponse.json()).data; categoryIds.push(category.id);
  expect((await POST(request({ action: "category", name: actor.toUpperCase() }))).status).toBe(409);
  const data = { ...input, subtitle: "A practical course", bannerUrl: "/images/home-hero-background-4.png", categoryId: category.id, instructorId, skillLevel: "intermediate", status: "published", accessType: "subscription", subscription: "Annual access, arranged offline", priceCents: 25000, enrollmentLimit: 25 };
  expect((await POST(request({ action: "update", id: draft.id, updatedAt: draft.updatedAt, data: { ...data, instructorId: randomUUID() } }))).status).toBe(422);
  expect((await POST(request({ action: "update", id: draft.id, updatedAt: draft.updatedAt, data: { ...data, categoryId: randomUUID() } }))).status).toBe(422);
  const savedResponse = await POST(request({ action: "update", id: draft.id, updatedAt: draft.updatedAt, data })); expect(savedResponse.status).toBe(200);
  const saved = (await savedResponse.json()).data;
  expect((await POST(request({ action: "update", id: draft.id, updatedAt: draft.updatedAt, data }))).status).toBe(409);
  const publicCourse = (await (await published()).json()).data.find((course: { id: string }) => course.id === draft.id);
  expect(publicCourse.subtitle).toBe(data.subtitle); expect(publicCourse.subscription).toBe(data.subscription);
  expect(publicCourse.instructor).toBe("Catalogue Fixture Instructor"); expect(publicCourse.instructorId).toBeUndefined();
  const copiedResponse = await POST(request({ action: "duplicate", id: saved.id, updatedAt: saved.updatedAt })); expect(copiedResponse.status).toBe(201);
  const copy = (await copiedResponse.json()).data; ids.push(copy.id);
  expect(copy.status).toBe("draft"); expect(copy.slug).not.toBe(saved.slug); expect(copy.bannerUrl).toBe(saved.bannerUrl);
  expect((await POST(request({ action: "delete", id: copy.id, updatedAt: copy.updatedAt }))).status).toBe(200);
  const offeringId = (await pool.query("insert into course_offerings(course_id,code,starts_at,ends_at,delivery_mode,is_published) values($1,$2,'2097-09-04','2097-09-05','virtual',true) returning id", [saved.id, actor])).rows[0].id;
  expect((await (await openOfferings()).json()).data.some((offering: { id: string }) => offering.id === offeringId)).toBe(true);
  const application = { offeringId, applicantName: "Catalogue Student", applicantEmail: "catalogue-student@example.test", participants: [{ name: "Catalogue Student", email: "catalogue-student@example.test" }], consent: true };
  const submitted = await register(new Request("http://localhost:3001/api/courses", { method: "POST", body: JSON.stringify(application) })); expect(submitted.status).toBe(201);
  expect((await pool.query("select name,email_normalized,status from registration_participants where offering_id=$1", [offeringId])).rows).toEqual([{ name: "Catalogue Student", email_normalized: "catalogue-student@example.test", status: "pending_review" }]);
  expect((await (await participants(request())).json()).data.registrations.some((row: { participantEmail: string; registration: { offeringId: string } }) => row.participantEmail === "catalogue-student@example.test" && row.registration.offeringId === offeringId)).toBe(true);
  expect((await POST(request({ action: "delete", id: saved.id, updatedAt: saved.updatedAt }))).status).toBe(409);
  const archived = await POST(request({ action: "update", id: saved.id, updatedAt: saved.updatedAt, data: { ...data, status: "archived" } })); expect(archived.status).toBe(200);
  expect((await (await published()).json()).data.some((course: { id: string }) => course.id === saved.id)).toBe(false);
  expect((await (await openOfferings()).json()).data.some((offering: { id: string }) => offering.id === offeringId)).toBe(false);
  expect((await register(new Request("http://localhost:3001/api/courses", { method: "POST", body: JSON.stringify({ ...application, applicantEmail: "another@example.test", participants: [{ name: "Another Student", email: "another@example.test" }] }) }))).status).toBe(409);
  const persisted = (await (await GET(request())).json()).data.find((course: { id: string }) => course.id === saved.id);
  expect(persisted.status).toBe("archived"); expect(persisted.enrollmentLimit).toBe(25);
  expect(persisted.skillLevel).toBe("intermediate"); expect(persisted.categoryId).toBe(category.id);
}, 30000);
