import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { afterAll, beforeAll, expect, it, vi } from "vitest";
let database: ReturnType<typeof drizzle>;
vi.mock("@/server/db", () => ({ getDb: () => database }));
vi.mock("@/server/auth", () => ({ getAuth: () => ({ api: { getSession: async ({ headers }: { headers: Headers }) => {
  const id = headers.get("x-test-user"); return id ? { user: { id, email: `${id}@example.test` } } : null;
} } }) }));
import { GET, POST } from "@/app/api/admin/student-posts/route";
import { GET as students } from "@/app/api/admin/students/route";
import { GET as portal, PATCH as updateProfile } from "@/app/api/portal/route";
const enabled = process.env.BOOKING_DB_TESTS === "1";
const suffix = randomUUID(); const actor = `post-admin-${suffix}`; const student = `post-student-${suffix}`; const other = `post-other-${suffix}`;
const ids = [actor, student, other, ...Array.from({ length: 26 }, (_, i) => `post-page-${i}-${suffix}`)];
let pool: Pool; let profileId: string; let otherProfileId: string;
const courseId = randomUUID(); const organisationId = randomUUID();
const req = (url = "http://localhost:3001/api/admin/student-posts", who = actor, body?: object, origin = "http://localhost:3001") => new Request(url, { method: body ? "POST" : "GET", headers: { origin, ...(who ? { "x-test-user": who } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
const listing = () => GET(req(`http://localhost:3001/api/admin/student-posts?profileId=${profileId}`));
beforeAll(async () => {
  if (!enabled) return;
  process.loadEnvFile(".env.local"); const u = new URL(process.env.DATABASE_URL!);
  if (!["localhost", "127.0.0.1"].includes(u.hostname) || u.port !== "55434" || u.pathname !== "/premium_web") throw new Error("Verified local database required.");
  pool = new Pool({ connectionString: process.env.DATABASE_URL }); database = drizzle(pool);
  for (const id of ids) {
    await pool.query('insert into "user"(id,name,email) values($1,$2,$3)', [id, `Post fixture ${suffix}`, `${id}@example.test`]);
    await pool.query("insert into profiles(auth_user_id,display_name,role) values($1,$2,$3)", [id, `Post fixture ${suffix}`, id === actor ? "client_admin" : "customer"]);
  }
  profileId = (await pool.query("select id from profiles where auth_user_id=$1", [student])).rows[0].id;
  otherProfileId = (await pool.query("select id from profiles where auth_user_id=$1", [other])).rows[0].id;
  await pool.query("insert into organisations(id,name) values($1,'Local post fixture')", [organisationId]);
  await pool.query("insert into organisation_memberships(organisation_id,profile_id,role) values($1,$2,'coordinator')", [organisationId, otherProfileId]);
  await pool.query("insert into courses(id,title,slug,summary,description) values($1,'Profile fixture',$2,'Private fixture','Private fixture')", [courseId, `post-${suffix}`]);
  const offeringId = (await pool.query("insert into course_offerings(course_id,code,starts_at,ends_at,delivery_mode,joining_instructions) values($1,$2,'2097-10-01','2097-10-02','virtual','Approved joining instructions') returning id", [courseId, `post-${suffix}`])).rows[0].id;
  const registrationId = (await pool.query("insert into course_registrations(offering_id,organisation_id,applicant_name,applicant_email,admin_notes) values($1,$2,'Applicant','private-applicant@example.test','PRIVATE ADMIN NOTE') returning id", [offeringId, organisationId])).rows[0].id;
  await pool.query("insert into registration_participants(registration_id,offering_id,profile_id,name,email,email_normalized,status) values($1,$2,$3,'Post student',$4,$4,'approved')", [registrationId, offeringId, profileId, `${student}@example.test`]);
  await pool.query("insert into course_materials(course_id,title,storage_key,original_filename,mime_type,size_bytes) values($1,'Profile material',$2,'workbook.txt','text/plain',10)", [courseId, `secret-storage-${suffix}`]);
  await pool.query("insert into course_invoices(registration_id,reference,amount_cents,notes,storage_key,original_filename) values($1,$2,100,'PRIVATE INVOICE NOTE',$3,'invoice.pdf')", [registrationId, `post-${suffix}`, `secret-invoice-${suffix}`]);
});
afterAll(async () => {
  if (!pool) return;
  await pool.query("delete from courses where id=$1", [courseId]); await pool.query("delete from organisations where id=$1", [organisationId]);
  await pool.query("delete from audit_logs where actor_auth_user_id=any($1::text[])", [ids]);
  await pool.query("delete from profiles where auth_user_id=any($1::text[])", [ids]); await pool.query('delete from "user" where id=any($1::text[])', [ids]); await pool.end();
});
it.skipIf(!enabled)("enforces targeted posts, publication, atomic versions and portal response privacy", async () => {
  const fields = { title: "Welcome note", body: "<script>Only text</script>\nYour course update.", isPublished: false };
  expect((await updateProfile(req("http://localhost:3001/api/portal", student, { action: "update_profile", displayName: "Student", timeZone: "Invalid/Zone" }))).status).toBe(422);
  expect((await updateProfile(req("http://localhost:3001/api/portal", student, { action: "update_profile", displayName: "Student", timeZone: "America/Jamaica" }, "https://untrusted.example"))).status).toBe(403);
  expect((await updateProfile(req("http://localhost:3001/api/portal", student, { action: "update_post", profileId, title: "Forbidden" }))).status).toBe(422);
  const create = { action: "create", profileId, data: fields };
  expect((await GET(req(undefined, ""))).status).toBe(401); expect((await GET(req(undefined, student))).status).toBe(403);
  expect((await POST(req(undefined, student, create))).status).toBe(403);
  expect((await POST(req(undefined, actor, create, "https://untrusted.example"))).status).toBe(403);
  expect((await POST(req(undefined, actor, { ...create, data: { ...fields, body: " " } }))).status).toBe(422);
  expect((await POST(req(undefined, actor, create))).status).toBe(201);
  const post = (await (await listing()).json()).data.posts[0];
  let view = await portal(req("http://localhost:3001/api/portal?scope=profile", student));
  expect(view.headers.get("cache-control")).toBe("private, no-store");
  let data = (await view.json()).data; expect(data.posts).toEqual([]);
  expect(data.materials).toHaveLength(1); expect(data.invoices).toHaveLength(1);
  expect(JSON.stringify(data)).not.toMatch(/storageKey|secret-storage|secret-invoice|adminNotes|PRIVATE ADMIN|PRIVATE INVOICE|private-applicant/);
  const update = { action: "update", profileId, id: post.id, updatedAt: post.updatedAt, data: { ...fields, isPublished: true } };
  expect((await POST(req(undefined, actor, { ...update, profileId: otherProfileId }))).status).toBe(404);
  expect((await POST(req(undefined, actor, update))).status).toBe(200);
  expect((await POST(req(undefined, actor, update))).status).toBe(409);
  data = (await (await portal(req("http://localhost:3001/api/portal?scope=profile", student))).json()).data;
  expect(data.posts[0].body).toBe(fields.body); expect(data.registrations[0].isOwn).toBe(true);
  view = await portal(req(`http://localhost:3001/api/portal?scope=profile&profileId=${profileId}`, other));
  const personal = (await view.json()).data; expect(personal.posts).toEqual([]); expect(personal.registrations).toEqual([]); expect(personal.materials).toEqual([]);
  const coordinated = (await (await portal(req("http://localhost:3001/api/portal", other))).json()).data;
  expect(coordinated.registrations).toHaveLength(1); expect(coordinated.materials).toHaveLength(1); expect(coordinated.posts).toEqual([]);
  expect(JSON.stringify(coordinated)).not.toMatch(/storageKey|adminNotes|PRIVATE ADMIN|secret-storage/);
  await pool.query("update registration_participants set status='pending_review' where profile_id=$1", [profileId]);
  data = (await (await portal(req("http://localhost:3001/api/portal?scope=profile", student))).json()).data;
  expect(data.materials).toEqual([]); expect(data.invoices).toHaveLength(1); expect(data.registrations[0].offering.joiningInstructions).toBeNull();
  const current = (await (await listing()).json()).data.posts[0];
  expect((await POST(req(undefined, actor, { action: "delete", profileId, id: post.id, updatedAt: post.updatedAt }))).status).toBe(409);
  expect((await POST(req(undefined, actor, { action: "delete", profileId, id: post.id, updatedAt: current.updatedAt }))).status).toBe(200);
  expect((await (await listing()).json()).data.posts).toEqual([]);
  const audit = (await pool.query("select metadata from audit_logs where actor_auth_user_id=$1", [actor])).rows;
  expect(audit).toHaveLength(3); expect(JSON.stringify(audit)).not.toContain(fields.body);
  await pool.query("update profiles set active=false where id=$1", [profileId]); expect((await listing()).status).toBe(404);
  expect((await POST(req(undefined, actor, create))).status).toBe(404);
  expect((await portal(req("http://localhost:3001/api/portal", student))).status).toBe(403);
});
it.skipIf(!enabled)("searches only active student accounts with bounded pagination", async () => {
  expect((await students(req(undefined, ""))).status).toBe(401); expect((await students(req(undefined, other))).status).toBe(403);
  const first = (await (await students(req(`http://localhost:3001/api/admin/students?search=${suffix}`))).json());
  expect(first.data).toHaveLength(25); expect(first.total).toBe(27);
  const second = (await (await students(req(`http://localhost:3001/api/admin/students?search=${suffix}&page=2`))).json());
  expect(second.data).toHaveLength(2); expect(new Set([...first.data, ...second.data].map((item) => item.id)).size).toBe(27);
  expect(first.data.some((item: { id: string }) => item.id === profileId)).toBe(false);
  expect((await students(req("http://localhost:3001/api/admin/students?page=-1"))).status).toBe(422);
});
