import { expect, request as playwrightRequest, test } from "@playwright/test";
import { randomBytes, randomUUID } from "node:crypto";
import { Pool } from "pg";
import { newBookingEvent } from "../src/lib/booking-events";

test.use({ trace: "off", screenshot: "off" });
test("signed-in booking calendar persists approval, edits, deletion and restoration", async ({ browser }) => {
  test.skip(process.env.BOOKING_DB_TESTS !== "1", "Opt in to isolated local database fixtures.");
  const url = new URL(process.env.DATABASE_URL!);
  const baseURL = process.env.COURSE_E2E_BASE_URL || "http://localhost:3001";
  if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.port !== "55434" || url.pathname !== "/premium_web" || new URL(baseURL).hostname !== "localhost") throw new Error("Local fixture targets required.");
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const suffix = randomUUID(); const eventId = randomUUID(); const bookingId = randomUUID();
  const email = `calendar-admin-${suffix}@example.test`;
  const context = await playwrightRequest.newContext({ baseURL });
  let userId = ""; let ui: Awaited<ReturnType<typeof browser.newContext>> | undefined;
  try {
    expect((await context.get("/api/admin/bookings/calendar?month=2096-09")).status()).toBe(401);
    const signup = await context.post("/api/auth/sign-up/email", { data: { name: "Fixture Administrator", email, password: randomBytes(24).toString("hex") } });
    expect(signup.status()).toBe(200);
    userId = (await pool.query('select id from "user" where email=$1', [email])).rows[0].id;
    expect((await context.get("/api/admin/bookings/calendar?month=2096-09")).status()).toBe(403);
    expect((await context.patch("/api/admin/bookings", { data: {} })).status()).toBe(403);
    await pool.query("update profiles set role='client_admin' where auth_user_id=$1", [userId]);
    await pool.query("insert into booking_events(id,slug,data) values($1,$2,$3)", [eventId, `calendar-live-${suffix}`, { ...newBookingEvent, title: "Calendar live fixture", slug: `calendar-live-${suffix}`, description: "Temporary local calendar verification fixture.", agentName: "Fixture Agent", agentPhoto: "/images/home-hero-background-4.png", leadTimeHours: 0, horizon: { unit: "infinite", count: 1 } }]);
    await pool.query("insert into appointments(id,booking_event_id,service,customer_name,customer_email,starts_at,ends_at,time_zone,questionnaire) values($1,$2,'Calendar live fixture','Calendar Test Client','fixture@example.test','2096-09-04T14:00:00Z','2096-09-04T14:30:00Z','America/Jamaica',$3)", [bookingId, eventId, { priority: "A delivery plan" }]);
    ui = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 }, storageState: await context.storageState() });
    const page = await ui.newPage();
    await page.goto("/admin/bookings");
    await page.getByLabel("Jump to month").fill("2096-09");
    await page.getByLabel("Availability for event").selectOption(eventId);
    await page.getByRole("button", { name: /September 4, 2096, 1 bookings/ }).click();
    await page.getByRole("button", { name: "Manage booking for Calendar Test Client" }).click();
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("Email customer about status or time changes").uncheck();
    await expect(dialog).toContainText("A delivery plan");
    await dialog.getByRole("button", { name: "Approve request" }).click();
    await expect(dialog.getByRole("combobox", { name: "Booking status", exact: true })).toHaveValue("confirmed");
    await dialog.getByRole("button", { name: "Edit details" }).click();
    await dialog.getByLabel("Admin notes", { exact: true }).fill("Local persistence verification.");
    await dialog.getByRole("button", { name: "Save details" }).click();
    await expect(dialog).toContainText("Local persistence verification.");
    await dialog.getByRole("button", { name: "Close booking" }).click();
    await page.reload();
    await page.getByRole("button", { name: "All requests", exact: true }).click();
    await page.getByLabel("Search bookings").fill("Calendar Test Client");
    await page.getByRole("button", { name: "Search", exact: true }).click();
    await page.getByRole("button", { name: "Manage booking for Calendar Test Client" }).click();
    await expect(page.getByRole("dialog")).toContainText("Local persistence verification.");
    await page.getByRole("button", { name: "Delete booking", exact: true }).click();
    await page.getByRole("button", { name: "Confirm move to Deleted bookings" }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.getByRole("button", { name: "Deleted bookings", exact: true }).click();
    await page.getByRole("button", { name: "Manage booking for Calendar Test Client" }).click();
    await page.getByRole("button", { name: "Restore booking", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    const persisted = (await pool.query("select status,notes,deleted_at,questionnaire from appointments where id=$1 and booking_event_id=$2", [bookingId, eventId])).rows[0];
    expect(persisted.status).toBe("confirmed"); expect(persisted.notes).toBe("Local persistence verification."); expect(persisted.deleted_at).toBeNull(); expect(persisted.questionnaire.priority).toBe("A delivery plan");
    await page.getByRole("button", { name: "Calendar", exact: true }).click();
    await page.getByLabel("Jump to month").fill("2096-09");
    await page.getByLabel("Availability for event").selectOption(eventId);
    await page.getByRole("button", { name: /September 4, 2096, 1 bookings/ }).click();
    await page.getByText("Edit availability for this date", { exact: true }).click();
    await page.getByRole("button", { name: "Remove time window 1" }).click();
    await page.getByRole("button", { name: "Close this date" }).click();
    await expect(page.getByRole("button", { name: /September 4, 2096, 1 bookings/ })).toHaveAccessibleName(/0 available times/);
    const savedEvent = (await pool.query("select data from booking_events where id=$1", [eventId])).rows[0].data;
    expect(savedEvent.dateOverrides).toEqual([{ date: "2096-09-04", windows: [] }]);
  } finally {
    await ui?.close(); await context.dispose();
    await pool.query("delete from appointments where id=$1 and booking_event_id=$2", [bookingId, eventId]);
    await pool.query("delete from audit_logs where actor_auth_user_id=$1", [userId]);
    await pool.query("delete from booking_events where id=$1", [eventId]);
    await pool.query("delete from profiles where auth_user_id=$1", [userId]);
    await pool.query('delete from "user" where email=$1', [email]);
    await pool.end();
  }
});
