import { expect, request as playwrightRequest, test } from "@playwright/test";
import { randomBytes, randomUUID } from "node:crypto";
import { Pool } from "pg";

test.use({ trace: "off", screenshot: "off" });
test("signed-in catalogue creation, editing, public visibility and deletion persist", async ({ browser }) => {
  test.skip(process.env.BOOKING_DB_TESTS !== "1", "Opt in to local database fixtures.");
  const url = new URL(process.env.DATABASE_URL!); const baseURL = process.env.COURSE_E2E_BASE_URL || "http://localhost:3001";
  if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.port !== "55434" || url.pathname !== "/premium_web" || new URL(baseURL).hostname !== "localhost") throw new Error("Verified local fixtures required.");
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const suffix = randomUUID(); const email = `catalogue-live-${suffix}@example.test`;
  const context = await playwrightRequest.newContext({ baseURL, extraHTTPHeaders: { origin: baseURL } });
  let userId = ""; let categoryId = ""; let ui: Awaited<ReturnType<typeof browser.newContext>> | undefined;
  const slug = `catalogue-live-${suffix}`;
  try {
    expect((await context.get("/api/admin/course-catalogue")).status()).toBe(401);
    expect((await context.post("/api/admin/course-catalogue", { data: {} })).status()).toBe(401);
    const signup = await context.post("/api/auth/sign-up/email", { data: { name: "Catalogue Live Fixture", email, password: randomBytes(24).toString("hex") } }); expect(signup.status()).toBe(200);
    userId = (await signup.json()).user.id;
    expect((await context.get("/api/admin/course-catalogue")).status()).toBe(403);
    expect((await context.post("/api/admin/course-catalogue", { data: {} })).status()).toBe(403);
    await pool.query("update profiles set role='client_admin' where auth_user_id=$1", [userId]);
    const instructor = (await pool.query("select id from profiles where auth_user_id=$1", [userId])).rows[0].id;
    const category = await context.post("/api/admin/course-catalogue", { data: { action: "category", name: `Live fixture ${suffix}` } }); expect(category.status()).toBe(201); categoryId = (await category.json()).data.id;
    ui = await browser.newContext({ baseURL, storageState: await context.storageState(), viewport: { width: 1440, height: 1000 } });
    const page = await ui.newPage(); await page.goto("/admin/courses");
    await page.getByRole("button", { name: "Upcoming courses" }).click(); await page.getByRole("button", { name: "Add New Course" }).click();
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("Course title", { exact: true }).fill(`Live catalogue ${suffix}`);
    await dialog.getByLabel("URL slug", { exact: true }).fill(slug);
    await dialog.getByLabel("Subtitle", { exact: true }).fill("Local verification only");
    await dialog.getByLabel("Short summary", { exact: true }).fill("Temporary course catalogue persistence check.");
    await dialog.getByLabel("Full description", { exact: true }).fill("A temporary test course. This is not a real advertised programme.");
    await dialog.getByLabel("Banner image URL").fill("/images/home-hero-background-4.png");
    await dialog.getByRole("combobox", { name: "Instructor", exact: true }).selectOption(instructor);
    await dialog.getByRole("combobox", { name: "Category", exact: true }).selectOption(categoryId);
    await dialog.getByRole("combobox", { name: "Publication status" }).selectOption("published");
    await dialog.getByRole("combobox", { name: "Access type" }).selectOption("subscription");
    await dialog.getByLabel("Subscription information").fill("Monthly course access arranged offline.");
    await dialog.getByRole("combobox", { name: "Currency", exact: true }).selectOption("CAD");
    await dialog.getByLabel("Course price", { exact: true }).fill("125.45");
    await dialog.getByRole("button", { name: "Save course", exact: true }).click(); await expect(dialog).toHaveCount(0);
    await page.reload(); await page.getByRole("button", { name: "Upcoming courses" }).click();
    await page.getByRole("button", { name: `Edit Live catalogue ${suffix}`, exact: true }).click();
    await expect(dialog.getByLabel("Subtitle", { exact: true })).toHaveValue("Local verification only");
    await expect(dialog.getByLabel("Course price", { exact: true })).toHaveValue("125.45");
    await expect(dialog.getByRole("combobox", { name: "Currency", exact: true })).toHaveValue("CAD");
    await expect(dialog.getByLabel("Subscription information")).toHaveValue("Monthly course access arranged offline.");
    expect((await pool.query("select access_type,price_cents,currency,subscription from courses where slug=$1", [slug])).rows[0]).toEqual({ access_type: "subscription", price_cents: 12545, currency: "CAD", subscription: "Monthly course access arranged offline." });
    await page.keyboard.press("Escape");
    await page.goto("/programmes"); await expect(page.getByRole("heading", { name: `Live catalogue ${suffix}`, exact: true })).toBeVisible();
    const card = page.locator(`#course-${slug}`); await expect(card.getByRole("button", { name: "Registration not open" })).toBeDisabled();
    await card.getByText("View course details", { exact: true }).click();
    await expect(card).toContainText("Subscription: Monthly course access arranged offline.");
    await page.goto("/admin/courses"); await page.getByRole("button", { name: "Upcoming courses" }).click();
    await page.getByRole("button", { name: `Edit Live catalogue ${suffix}`, exact: true }).click();
    await dialog.getByRole("combobox", { name: "Access type" }).selectOption("one_time");
    await dialog.getByLabel("Course price", { exact: true }).fill("0.01");
    await dialog.getByRole("button", { name: "Save course", exact: true }).click(); await expect(dialog).toHaveCount(0);
    await page.goto("/programmes"); await card.getByText("View course details", { exact: true }).click();
    await expect(card).not.toContainText("Monthly course access arranged offline.");
    expect((await pool.query("select access_type,price_cents,subscription from courses where slug=$1", [slug])).rows[0]).toEqual({ access_type: "one_time", price_cents: 1, subscription: "Monthly course access arranged offline." });
    await page.goto("/admin/courses"); await page.getByRole("button", { name: "Upcoming courses" }).click();
    await page.getByRole("button", { name: `Edit Live catalogue ${suffix}`, exact: true }).click();
    await dialog.getByRole("combobox", { name: "Access type" }).selectOption("private");
    await dialog.getByRole("button", { name: "Save course", exact: true }).click(); await expect(dialog).toHaveCount(0);
    await page.goto("/programmes"); await expect(card).toHaveCount(0);
    await page.goto("/admin/courses"); await page.getByRole("button", { name: "Upcoming courses" }).click();
    await page.getByRole("button", { name: `Edit Live catalogue ${suffix}`, exact: true }).click();
    await dialog.getByRole("combobox", { name: "Publication status" }).selectOption("archived"); await dialog.getByRole("button", { name: "Save course", exact: true }).click(); await expect(dialog).toHaveCount(0);
    expect((await pool.query("select status,is_active from courses where slug=$1", [slug])).rows[0]).toEqual({ status: "archived", is_active: false });
    await page.goto("/programmes"); await expect(page.locator(`#course-${slug}`)).toHaveCount(0);
    await page.goto("/admin/courses"); await page.getByRole("button", { name: "Upcoming courses" }).click();
    await page.getByRole("button", { name: `Delete Live catalogue ${suffix}`, exact: true }).click(); await page.getByRole("button", { name: "Confirm delete", exact: true }).click();
    await expect(page.getByRole("button", { name: `View Live catalogue ${suffix}`, exact: true })).toHaveCount(0);
    expect((await pool.query("select id from courses where slug=$1", [slug])).rows).toHaveLength(0);
  } finally {
    await ui?.close(); await context.dispose();
    await pool.query("delete from courses where slug=$1", [slug]);
    if (categoryId) await pool.query("delete from course_categories where id=$1", [categoryId]);
    if (userId) { await pool.query("delete from audit_logs where actor_auth_user_id=$1", [userId]); await pool.query("delete from profiles where auth_user_id=$1", [userId]); await pool.query('delete from "user" where id=$1', [userId]); }
    await pool.end();
  }
});
