"use client";

import { Award, BookOpen, Building2, CalendarDays, Download, FileText, LayoutDashboard, LoaderCircle, LogOut, MapPin, Menu, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

import { BrandLogo } from "@/components/brand-logo";
import { authClient } from "@/lib/auth-client";
import { formatMoney } from "@/lib/courses";

type PortalData = { user: { name: string; email: string }; memberships: { organisationId: string; role: string; organisationName: string }[]; registrations: { participant: { id: string; profileId: string | null; name: string; email: string; status: string; attendance: string; cancellationRequestedAt: string | null }; registration: { id: string; organisationId: string | null; paymentStatus: string; amountDueCents: number }; offering: { id: string; code: string; startsAt: string; timeZone: string; deliveryMode: string; venue: string | null; substitutionCutoffAt: string | null }; course: { id: string; title: string }; organisationName: string | null }[]; materials: { id: string; title: string; originalFilename: string; mimeType: string; sizeBytes: number; createdAt: string }[]; invoices: { id: string; documentType: "invoice" | "receipt"; reference: string; amountCents: number; dueAt: string | null }[]; certificates: { id: string; certificateNumber: string; courseTitle: string; issuedAt: string }[] };

function Status({ value }: { value: string }) { return <span className={`course-status course-status--${value}`}>{value.replaceAll("_", " ")}</span>; }

export function ClientCoursePortal() {
  const [data, setData] = useState<PortalData | null>(null); const [message, setMessage] = useState("Loading your course portal…"); const [menuOpen, setMenuOpen] = useState(false); const [replacingId, setReplacingId] = useState("");
  async function load() { const response = await fetch("/api/portal", { cache: "no-store" }); if (response.status === 401) { window.location.assign("/portal/login"); return; } const result = await response.json() as { data?: PortalData; error?: { message?: string } }; if (!response.ok || !result.data) { setMessage(result.error?.message || "Portal data could not be loaded."); return; } setData(result.data); setMessage(""); }
  useEffect(() => { fetch("/api/portal", { cache: "no-store" }).then(async (response) => { if (response.status === 401) { window.location.assign("/portal/login"); return null; } const result = await response.json() as { data?: PortalData; error?: { message?: string } }; if (!response.ok || !result.data) throw new Error(result.error?.message || "Portal data could not be loaded."); return result.data; }).then((result) => { if (result) { setData(result); setMessage(""); } }).catch((error) => setMessage(error instanceof Error ? error.message : "Portal data could not be loaded.")); }, []);
  async function signOut() { await authClient.signOut(); window.location.assign("/portal/login"); }
  async function requestCancellation(id: string) { await fetch("/api/portal", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "cancel_request", participantId: id }) }); await load(); }
  async function addParticipant(event: FormEvent<HTMLFormElement>, registrationId: string) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/portal", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "add_participant", registrationId, name: form.get("name"), email: form.get("email"), phone: form.get("phone") }) }); if (response.ok) { event.currentTarget.reset(); await load(); } else { const result = await response.json() as { error?: { message?: string } }; setMessage(result.error?.message || "Participant could not be added."); } }
  async function replaceParticipant(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/portal", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "replace_participant", participantId: replacingId, name: form.get("name"), email: form.get("email"), phone: form.get("phone") }) }); if (response.ok) { setReplacingId(""); await load(); setMessage("Participant replacement submitted for review."); } else { const result = await response.json() as { error?: { message?: string } }; setMessage(result.error?.message || "Participant could not be replaced."); } }
  if (!data) return <main className="portal-loading"><LoaderCircle className="spin" aria-hidden="true" /><h1>Client course portal</h1><p>{message}</p></main>;
  const own = data.registrations.filter((row) => row.participant.email.toLowerCase() === data.user.email.toLowerCase());
  const next = own.find((row) => new Date(row.offering.startsAt) > new Date() && ["approved", "completed"].includes(row.participant.status));
  const coordinator = data.memberships.some((row) => row.role === "coordinator");
  const organisationRegistration = coordinator ? data.registrations.find((row) => row.registration.organisationId) : undefined;
  return <main className="client-portal"><aside className={menuOpen ? "is-open" : ""}><Link className="client-portal__brand" href="/"><BrandLogo className="brand-logo__image" priority /></Link><nav><a className="active" href="#dashboard"><LayoutDashboard /> Dashboard</a><a href="#courses"><BookOpen /> My courses</a>{coordinator && <a href="#organisation"><Building2 /> Organisation</a>}<a href="#documents"><FileText /> Documents</a><Link href="/portal/profile"><UserRound /> Profile</Link></nav><button onClick={signOut}><LogOut /> Sign out</button></aside><section className="client-portal__main"><header><button className="client-portal__menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle portal menu"><Menu /></button><div><strong>{data.user.name}</strong><span>{data.memberships[0]?.organisationName || "Participant"}</span></div></header><div className="client-portal__content" id="dashboard"><h1>Welcome back, {data.user.name.split(" ")[0]}.</h1>
    <div className="portal-feature-row">{next ? <section className="portal-upcoming"><span>Upcoming course</span><div><CalendarDays /><div><h2>{next.course.title}</h2><p><Status value={next.participant.status} /> {new Date(next.offering.startsAt).toLocaleString("en-JM", { dateStyle: "medium", timeStyle: "short", timeZone: next.offering.timeZone })} · <MapPin /> {next.offering.venue || next.offering.deliveryMode.replaceAll("_", " ")}</p></div></div></section> : <section className="portal-upcoming"><h2>No upcoming approved courses</h2><p>Your approved registrations will appear here.</p></section>}{data.certificates[0] && <section className="portal-certificate"><Award /><div><h2>Certificate available</h2><p>{data.certificates[0].courseTitle}</p><a href={`/api/portal/downloads/certificate/${data.certificates[0].id}`}><Download /> Download certificate</a></div></section>}</div>
    <div className="portal-grid"><section className="portal-panel" id="documents"><header><h2>Materials</h2></header><div className="portal-document-list">{data.materials.map((material) => <div key={material.id}><FileText /><div><strong>{material.title}</strong><span>{material.originalFilename} · {(material.sizeBytes / 1024).toFixed(0)} KB</span></div><a href={`/api/portal/downloads/material/${material.id}`}><Download /> Download</a></div>)}{!data.materials.length && <p>No materials are available yet.</p>}</div></section>
    {coordinator && <section className="portal-panel" id="organisation"><header><h2>Organisation roster</h2><span>{data.memberships[0]?.organisationName}</span></header><div className="portal-roster">{data.registrations.filter((row) => row.registration.organisationId).map((row) => <div key={row.participant.id}><span className="portal-avatar">{row.participant.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><div><strong>{row.participant.name}</strong><span>{row.participant.email}</span></div><Status value={row.participant.status} /><button className="course-table-action" type="button" onClick={() => setReplacingId(row.participant.id)}>Replace</button></div>)}</div>{replacingId && <form className="portal-add-person" onSubmit={replaceParticipant}><h3>Replace selected participant</h3><input name="name" placeholder="Replacement full name" required /><input name="email" type="email" placeholder="Replacement email" required /><input name="phone" placeholder="Phone" /><button type="submit">Submit replacement</button><button type="button" onClick={() => setReplacingId("")}>Cancel</button></form>}{organisationRegistration && <form className="portal-add-person" onSubmit={(event) => addParticipant(event, organisationRegistration.registration.id)}><h3>Add participant</h3><input name="name" placeholder="Full name" required /><input name="email" type="email" placeholder="Email" required /><input name="phone" placeholder="Phone" /><button type="submit">Add to roster</button></form>}</section>}</div>
    <section className="portal-panel portal-registrations" id="courses"><header><h2>My registrations</h2></header><div className="portal-table-wrap"><table><thead><tr><th>Course</th><th>Date</th><th>Registration</th><th>Payment</th><th>Action</th></tr></thead><tbody>{own.map((row) => <tr key={row.participant.id}><td><strong>{row.course.title}</strong><span>{row.offering.code}</span></td><td>{new Date(row.offering.startsAt).toLocaleDateString("en-JM", { dateStyle: "medium", timeZone: row.offering.timeZone })}</td><td><Status value={row.participant.status} /></td><td><Status value={row.registration.paymentStatus} /> <span>{formatMoney(row.registration.amountDueCents)}</span></td><td>{!row.participant.cancellationRequestedAt && ["pending_review", "approved", "waitlisted"].includes(row.participant.status) ? <button onClick={() => requestCancellation(row.participant.id)}>Request cancellation</button> : row.participant.cancellationRequestedAt ? "Requested" : "—"}</td></tr>)}</tbody></table></div></section>
    {data.invoices.length > 0 && <section className="portal-panel"><header><h2>Payment documents</h2></header><div className="portal-document-list">{data.invoices.map((invoice) => <div key={invoice.id}><FileText /><div><strong>{invoice.reference}</strong><span>{invoice.documentType === "receipt" ? "Receipt" : "Invoice"} · {formatMoney(invoice.amountCents)}{invoice.dueAt && invoice.documentType === "invoice" ? ` · Due ${new Date(invoice.dueAt).toLocaleDateString("en-JM")}` : ""}</span></div><a href={`/api/portal/downloads/${invoice.documentType}/${invoice.id}`}><Download /> Download</a></div>)}</div></section>}
  </div></section></main>;
}
