import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = { title: "Terms and Conditions", description: "Terms governing use of the CH Elevate website, services, accounts and course portal." };

export default function TermsPage() {
  return <LegalDocument title="Terms and Conditions" summary="These terms govern your use of our website, registration portal, course resources and related services.">
    <section><h2>1. About these terms</h2><p>These Terms and Conditions apply when you visit or use the CH Elevate Consultancy Limited website, submit an enquiry or booking, create an account, register for a course, or access resources through our portal. By using these services, you agree to these terms.</p><p>If a proposal, invoice, registration confirmation, engagement letter or other written agreement issued by CH Elevate contains terms that differ from this page, that specific agreement will control for the relevant service.</p></section>
    <section><h2>2. Website information and consulting services</h2><p>Website content is provided for general information. It does not create a consulting engagement, professional-client relationship or binding commitment. An enquiry or requested consultation is not confirmed until an authorised CH Elevate representative accepts it in writing.</p><p>Service scope, deliverables, timing and fees will be stated in the applicable proposal, quotation or engagement agreement. You are responsible for providing accurate, timely information needed for us to perform the agreed work.</p></section>
    <section><h2>3. Course registration and approval</h2><p>Submitting a course application does not guarantee a place. Applications may be reviewed for eligibility, capacity and administrative requirements. We may approve, waitlist or reject an application, and we will communicate the outcome using the contact details supplied.</p><p>Course dates, venue, delivery format, fees, registration windows and capacity may vary by offering. An organisation coordinator is responsible for submitting accurate participant information and obtaining any permissions required to share it.</p></section>
    <section><h2>4. Accounts and portal access</h2><p>You must provide accurate account and profile information, keep your login credentials confidential and notify us promptly if you suspect unauthorised access. Accounts are personal and may not be shared.</p><p>Approved participants may access materials assigned to their course. Waitlisted, rejected or cancelled registrations do not receive protected course access. We may suspend access where reasonably necessary to protect the portal, investigate misuse or enforce these terms.</p></section>
    <section><h2>5. Fees, invoices and refunds</h2><p>Course and service fees are payable according to the relevant invoice or written agreement. The portal records offline payment information but does not process card payments. Approval and payment status are separate administrative matters unless your course-specific terms state otherwise.</p><p>Cancellations, transfers and refunds are governed by our Refund Policy and any course-specific terms supplied before payment.</p></section>
    <section><h2>6. Course materials and intellectual property</h2><p>Unless we state otherwise in writing, website content, course materials, certificates, branding, graphics and other resources are owned by or licensed to CH Elevate. Approval for a course gives the participant a limited, personal, non-exclusive and non-transferable right to use assigned materials for their own learning.</p><p>You may not sell, publish, reproduce, distribute, upload, share access to, remove ownership notices from, or create commercial derivatives of protected materials without prior written permission. Organisation coordinators may download materials only for the approved cohort and within the permissions shown in the portal.</p></section>
    <section><h2>7. Acceptable use</h2><p>You must not misuse the website or portal, attempt to bypass access controls, interfere with its operation, introduce malicious code, scrape protected information, impersonate another person, submit unlawful content, or use another person&apos;s account or records without authority.</p></section>
    <section><h2>8. Course changes and participant conduct</h2><p>We may make reasonable changes to facilitators, schedules, venues, delivery methods or materials. If we cancel an offering, the remedies in our Refund Policy apply. Participants must behave respectfully and follow reasonable safety, venue and participation instructions. Serious or repeated misconduct may result in removal, subject to applicable law and any course-specific terms.</p></section>
    <section><h2>9. Third-party services and links</h2><p>The website may link to or rely on third-party services. We do not control third-party content, availability or privacy practices. Your use of those services may be subject to separate terms.</p></section>
    <section><h2>10. Disclaimers and liability</h2><p>We aim to keep information and services accurate and available, but cannot guarantee uninterrupted or error-free operation. Course participation, materials and certificates do not guarantee employment, promotion, accreditation or a particular business outcome unless expressly stated in writing.</p><p>To the fullest extent permitted by applicable law, CH Elevate will not be liable for indirect or consequential loss arising from use of the website or portal. Nothing in these terms excludes liability or rights that cannot lawfully be excluded.</p></section>
    <section><h2>11. Changes, governing law and contact</h2><p>We may update these terms when our services or legal obligations change. The updated version will be posted here with a revised date. These terms are governed by the laws of Jamaica, and disputes are subject to the jurisdiction of the Jamaican courts unless a binding agreement provides otherwise.</p><p>Questions may be sent to <a href="mailto:info@ch-elevateconsultancy.com">info@ch-elevateconsultancy.com</a>.</p></section>
  </LegalDocument>;
}
