import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = { title: "Data Protection", description: "CH Elevate data-protection practices under Jamaica's Data Protection Act, 2020." };

export default function DataProtectionPage() {
  return <LegalDocument title="Data Protection" summary="Our approach to handling personal data in line with Jamaica’s Data Protection Act, 2020.">
    <section><h2>1. Our commitment</h2><p>CH Elevate Consultancy Limited aims to process personal data responsibly and in accordance with Jamaica&apos;s Data Protection Act, 2020 and applicable regulations. This statement describes our operational approach and should be read with our Privacy Policy.</p></section>
    <section><h2>2. Data-protection standards</h2><p>Our data-handling practices are guided by the Act&apos;s eight standards. Personal data should be:</p><ol><li>processed fairly and lawfully;</li><li>obtained for specified, lawful purposes and not used incompatibly;</li><li>adequate, relevant and limited to what is necessary;</li><li>accurate and kept up to date where necessary;</li><li>kept no longer than needed for its purpose;</li><li>processed in accordance with the rights of data subjects;</li><li>protected by appropriate technical and organisational measures; and</li><li>transferred outside Jamaica only where the required level of protection is addressed.</li></ol></section>
    <section><h2>3. Accountability and purpose</h2><p>We identify why personal data is needed before collecting it, limit access according to job responsibilities, and use data for stated business, course-administration, security and legal purposes. We assess controller registration, data-protection-officer and impact-assessment obligations and will meet them where they apply to our operations.</p></section>
    <section><h2>4. Individual and organisation records</h2><p>Individual applicants may provide their own data. For organisation-sponsored registration, an authorised coordinator may submit participant information and monitor the organisation&apos;s registration and payment records. Coordinators are limited to their own organisation and do not receive participant passwords or private individual certificates.</p><p>Approval controls access to protected materials. Registration decisions and offline payment status are maintained as separate records. Administrative actions and protected downloads may be recorded for accountability and security.</p></section>
    <section><h2>5. Your rights</h2><p>Subject to the Act and its exceptions, you may be entitled to:</p><ul><li>receive information about how your personal data is used;</li><li>request access to personal data held about you;</li><li>have inaccurate or incomplete data corrected;</li><li>object to or prevent certain processing, including direct marketing;</li><li>withdraw consent where processing depends on consent;</li><li>request transfer of data where the legal requirements are met;</li><li>receive information about certain automated decisions and request human review; and</li><li>complain to the Office of the Information Commissioner.</li></ul></section>
    <section><h2>6. How to make a request</h2><p>Email <a href="mailto:info@ch-elevateconsultancy.com?subject=Data%20protection%20request">info@ch-elevateconsultancy.com</a> with the subject “Data protection request”. Describe the information or action requested and provide a reliable way to contact you. We may ask for information needed to verify your identity and authority, particularly where a coordinator or representative makes the request.</p><p>We will acknowledge and respond within the period required by applicable law. A request may be limited or refused where the Act permits, in which case we will explain the basis where legally allowed.</p></section>
    <section><h2>7. Security and access controls</h2><p>Our safeguards include role-based administrative access, authenticated participant and coordinator access, private storage for uploaded course files, authorisation checks before downloads, non-guessable file references, file-type and size restrictions, version records, and audit logging for relevant administrative and download activity.</p><p>We also use account-verification and password-reset controls and restrict course materials from registrations that are waitlisted, rejected or cancelled. Safeguards are reviewed according to risk and changes in the service.</p></section>
    <section><h2>8. Retention and disposal</h2><p>We review the need for personal data and retain it only while necessary for service delivery, course history, certificates, security, disputes, audits and legal or financial recordkeeping. When data is no longer required, we delete, anonymise or securely dispose of it, subject to backup lifecycles and lawful retention needs.</p></section>
    <section><h2>9. Service providers and overseas transfers</h2><p>Technology and professional service providers may process limited data on our behalf. We select providers and use contractual, access and security controls appropriate to the service. Before a relevant overseas transfer, we consider the destination&apos;s protection and any safeguards required by Jamaican law.</p></section>
    <section><h2>10. Personal-data incidents</h2><p>Suspected loss, misuse, unauthorised access or disclosure is assessed and contained through our incident process. We document relevant facts, take corrective action, and notify the Information Commissioner and affected individuals when and within the timeframe required by law.</p></section>
    <section><h2>11. Concerns and complaints</h2><p>Please contact us first so we can try to resolve your concern. You may also contact the <a href="https://oic.gov.jm/" target="_blank" rel="noreferrer">Office of the Information Commissioner of Jamaica</a>, the independent regulator responsible for oversight of the Data Protection Act.</p><p>This statement is a practical description of our approach and is not legal advice. We may update it as our operations, guidance or applicable law changes.</p></section>
  </LegalDocument>;
}
