import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = { title: "Privacy Policy", description: "How CH Elevate collects, uses, shares and protects personal data." };

export default function PrivacyPage() {
  return <LegalDocument title="Privacy Policy" summary="This policy explains the personal information we collect, why we use it and the choices available to you.">
    <section><h2>1. Who we are</h2><p>CH Elevate Consultancy Limited provides consulting, training and related services. For personal data collected through this website and portal, CH Elevate is generally the data controller. This policy should be read with our Data Protection statement.</p></section>
    <section><h2>2. Information we collect</h2><p>Depending on how you use our services, we may collect:</p><ul><li>identity and contact details, including your name, email address, phone number, country and organisation;</li><li>account and profile details, including job title, time zone and authentication records;</li><li>enquiry, booking, course application and participant-roster information;</li><li>registration status, attendance, completion, certificates and course-material download activity;</li><li>offline payment, invoice, receipt and administrative information;</li><li>communications, support requests, cancellation requests and marketing preferences; and</li><li>technical and security information such as session, device, browser, IP address and audit-log data.</li></ul><p>We do not use this website to process payment-card details. Passwords are handled by the authentication system and are not stored as readable text.</p></section>
    <section><h2>3. How we collect information</h2><p>We collect information directly from you, from an authorised organisation coordinator registering participants, through your use of the website and portal, and from service providers supporting our operations. If you provide another person&apos;s information, you must be authorised to do so and should make this policy available to them.</p></section>
    <section><h2>4. Why we use personal data</h2><p>We use personal data to respond to enquiries, manage bookings and consulting engagements, create and secure accounts, assess and administer course registrations, manage capacity and waitlists, issue invoices and receipts, provide private materials, record attendance, issue and verify certificates, send service notifications, maintain business records, improve service reliability, prevent misuse and meet legal obligations.</p><p>Where applicable, our grounds for processing may include your consent, steps requested before a contract, performance of a contract, compliance with a legal obligation, and our legitimate interests in operating and protecting the business. We will seek specific consent or rely on another lawful condition where the law requires it.</p></section>
    <section><h2>5. Sharing personal data</h2><p>We may share only the information reasonably necessary with technology, hosting, email and professional service providers; authorised CH Elevate personnel; an organisation coordinator acting for the participant&apos;s organisation; and regulators, courts or public authorities where legally required. Coordinators are restricted to records belonging to their organisation and cannot access individual participant credentials or certificates.</p><p>We do not sell personal data. Providers acting for us are expected to protect information and use it only for the agreed service.</p></section>
    <section><h2>6. Cookies and similar technology</h2><p>We use cookies or comparable storage that is necessary for account authentication, session security and core website operation. If we introduce non-essential analytics or advertising technology, we will update our notice and provide any choice required by law.</p></section>
    <section><h2>7. International processing</h2><p>Some service providers may process information outside Jamaica. Where a transfer is subject to Jamaican data-protection requirements, we will assess the destination and use appropriate contractual, organisational or other safeguards.</p></section>
    <section><h2>8. Retention and security</h2><p>We keep personal data only for as long as needed for the purpose collected, the service relationship, security, dispute handling, audit and applicable legal or financial recordkeeping requirements. Retention varies by record type, and backups are removed or overwritten through their normal lifecycle.</p><p>We use role-based access, authenticated downloads, private file storage, audit records and other technical and organisational measures appropriate to the information. No system is completely secure, but we review protections and respond to suspected incidents.</p></section>
    <section><h2>9. Your rights</h2><p>Subject to the Data Protection Act, 2020 and applicable exceptions, you may have rights to be informed, request access, correct inaccurate data, object to or restrict certain processing, withdraw consent, prevent direct marketing, address certain automated decisions, request transfer of data and complain to the Information Commissioner.</p><p>See our Data Protection statement for request details.</p></section>
    <section><h2>10. Children&apos;s information</h2><p>Our general website and services are not directed to children. We will not knowingly collect a child&apos;s personal data without appropriate authority or consent where required. A guardian or sponsoring organisation should contact us before submitting a minor&apos;s information.</p></section>
    <section><h2>11. Updates and contact</h2><p>We may update this policy to reflect service, technology or legal changes. For privacy questions or requests, email <a href="mailto:info@ch-elevateconsultancy.com?subject=Data%20protection%20request">info@ch-elevateconsultancy.com</a> with the subject “Data protection request”. We may need to verify your identity before acting on a request.</p></section>
  </LegalDocument>;
}
