import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = { title: "Refund Policy", description: "CH Elevate cancellation, transfer and refund policy." };

export default function RefundPolicyPage() {
  return <LegalDocument title="Refund Policy" summary="This policy explains how cancellations, course transfers and refund requests are handled.">
    <section><h2>1. Scope</h2><p>This policy applies to course registration fees and service payments made to CH Elevate Consultancy Limited unless a proposal, invoice, registration confirmation or other written agreement provides different terms. Those specific written terms will control where they differ.</p></section>
    <section><h2>2. Before making payment</h2><p>Please review the course or service description, dates, delivery method, fees and any cancellation terms shown on your invoice or confirmation. Payments are handled offline; this website does not process payment cards.</p></section>
    <section><h2>3. If CH Elevate cancels</h2><p>If we cancel a paid course and do not provide an acceptable rescheduled date, you may choose a transfer or credit toward another available offering, or a refund of the amount paid for the cancelled course. If we cannot deliver a paid consulting service, the applicable agreement and work already completed will be considered when determining any refund.</p></section>
    <section><h2>4. Participant cancellation</h2><p>To cancel, email us as early as possible and include the participant name, course, offering date, organisation if applicable, and invoice or payment reference. If no course-specific cancellation schedule was supplied, we will consider a refund or credit where the request is received before the course begins and before protected materials or substantial services have been provided.</p><p>Fees are normally non-refundable after a course has begun, after a participant has attended, or after substantial course materials or services have been delivered, except where required by law or where CH Elevate agrees otherwise in writing.</p></section>
    <section><h2>5. Transfers and participant substitutions</h2><p>Where capacity and course requirements allow, we may offer a transfer to another scheduled offering or permit an organisation to substitute an eligible participant before the stated cutoff. Transfers and substitutions require written approval and may be limited where personalised materials, certificates, venue costs or other commitments have already been arranged.</p></section>
    <section><h2>6. Waitlisted and rejected applications</h2><p>Submitting an application does not guarantee approval. Applicants should not pay unless instructed to do so. If CH Elevate received a payment for an application that is later rejected or remains waitlisted without a confirmed place, we will arrange a refund or, with the payer&apos;s agreement, a transfer or credit.</p></section>
    <section><h2>7. No-shows and access problems</h2><p>Failure to attend without notice is not normally refundable. If a participant cannot access an online session or assigned materials because of a CH Elevate technical issue, contact us promptly so we can investigate and provide restored access, an alternative delivery, a transfer, credit or refund as appropriate.</p></section>
    <section><h2>8. Refund method and timing</h2><p>Approved refunds will normally be returned to the original payer using a reasonable available method. We will confirm the approved amount and expected processing time in writing. Bank, transfer or currency charges outside our control may affect the amount received unless applicable law requires otherwise.</p></section>
    <section><h2>9. Requesting a refund</h2><p>Email <a href="mailto:info@ch-elevateconsultancy.com?subject=Refund%20request">info@ch-elevateconsultancy.com</a> with the subject “Refund request”. Include enough information for us to identify the registration or service and the reason for the request. This policy does not limit any non-excludable rights or remedies under Jamaican law.</p></section>
  </LegalDocument>;
}
